version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR started on $(date)"
      - aws --version
      - echo "Retrieving ECR repository URI and region from Parameter Store..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - ECR_REPOSITORY_URI=$ECR_REPOSITORY_URI
      - AWS_REGION=$AWS_REGION
      - echo "Logging into ECR..."
      - echo "Setting image tag..."
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Building and tagging started on $(date)"
      - echo "Running mvn clean install..."
      - mvn clean install
      - echo "Building the Docker images..."
      - docker-compose -f docker-compose.yml build
      - echo "Tagging the Docker images..."
      - docker tag api-gateway:latest $ECR_REPOSITORY_URI:api-gateway-latest
      - docker tag api-gateway:latest $ECR_REPOSITORY_URI:api-gateway-$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker images to Amazon ECR started on $(date)"
      - echo "Pushing to repository..."
      - docker push $ECR_REPOSITORY_URI:api-gateway-latest
      - docker push $ECR_REPOSITORY_URI:api-gateway-$IMAGE_TAG
      - echo "Setting container name..."
      - DOCKER_CONTAINER_NAME=api-gateway
      - echo "Writing image definitions file..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $ECR_REPOSITORY_URI:api-gateway-$IMAGE_TAG > imagedefinitions.json
      - echo "Printing imagedefinitions.json"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
