version: "3.9"

services:
  mongo:
    image: mongo:7.0.9
    container_name: "gws-mongo"
    ports:
      - "27017:27017"

  consul:
    image: bitnami/consul
    container_name: "gws-consul"
    ports:
      - "8500:8500"
    command: "consul agent -dev -ui -client=0.0.0.0"

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: "gws-elasticsearch"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "gws-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "s@cr3t"
    ports:
      - "5673:5673"
      - "15673:15673"

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: api-gateway
    ports:
      - "2035:2035"
    depends_on:
      - rabbitmq
      - elasticsearch
      - consul
      - mongo
    environment:
      FRONT-END-URI: ${FRONT_END_URI}
      OAUTH-GOOGLE-CLIENT-ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH-GOOGLE-CLIENT-SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      CONSUL-HOST: consul
      CONSUL-PORT: 8500
      DISH-SERVICE-URI: ${DISH_SERVICE_URI}
      REDIRECT-URL: ${REDIRECT_URL}

networks:
  default:
    name: app-network
    external: true

