server:
  port: 2035
  error:
    include-message: always
    include-binding-errors: always

frontend-uri: ${FRONT-END-URI}
redirect-url: ${REDIRECT-URL}

oauth:
  google:
    clientId: ${OAUTH-GOOGLE-CLIENT-ID}
    clientSecret: ${OAUTH-GOOGLE-CLIENT-SECRET}
    scope: "openid profile email"

spring:
  application:
    name: gateway
  config:
    import: optional:consul:/
  cloud:
    gateway:
      routes:
        - id: gateway-oauth-route
          uri: lb://gateway
          predicates:
            - Path=/oauth/**
        - id: service-dishes-route
          uri: ${DISH-SERVICE-URI}
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<remaining>.*), /api/${remaining}
        - id: service-reviews-route
          uri: http://localhost:8888
          predicates:
            - Path=/api/reviews/**
          filters:
            - RewritePath=/api/reviews/(?<remaining>.*), /api/reviews/${remaining}
  r2dbc:
    url: "r2dbc:h2:mem:///gwsdb"
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
